Impl. Service for AddTopic handling and axios call
timlenny/cgn-java-23-1-capstone pull request #13
Opened 2023-03-21 15:15 UTC by timlenny

Service that handles adding new topics and made adjustments in the frontend

2023-03-21 22:16 UTC, MoinMarcell requested changes
You have a Codesmell in the backend and you only tested the [TopicConversionService](https://sonarcloud.io/component_measures?id=timlenny_cgn-java-23-1-capstone_backend&pullRequest=13&metric=new_coverage&view=list&selected=timlenny_cgn-java-23-1-capstone_backend%3Asrc%2Fmain%2Fjava%2Fcom%2Ftimlenny%2Fbackend%2Fservice%2FTopicConversionService.java) particually. For a review contact us in slack if you have fixed it.

2023-03-22 15:04 UTC, HendrikNeuschulz approved these changes
for me, there is nothing to change here.

2023-03-22 15:30 UTC, MoinMarcell approved these changes
lgtm

2023-03-22 15:30 UTC, MoinMarcell commented on backend/src/main/java/com/timlenny/backend/repository/TopicRepository.java
>  }
no new line

2023-03-22 15:34 UTC, merged